Team-LionHeart/LionHeart-iOS

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Global/Enums/NavigationBarType.swift, LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIApplication+.swift, LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift, LionHeart-iOS/LionHeart-iOS/Global/Utils/NavigationBarLayoutManager.swift, LionHeart-iOS/LionHeart-iOS/Global/Utils/ScreenUtils.swift
- NavigationBar 구현 (에셋이랑 폰트 모두 임시입니다.)
```swift
private lazy var navigationBar = LHNavigationBarView(type: .today, viewController: self)
.rightFirstBarItemAction {
print("first bar item tapped")
}
.rightSecondBarItemAction {
print("second bar item tapped")
}
```
- type에 본인의 뷰에 맞는 타입을 넣고 viewController에 self를 넣어주시면 됩니다. (lazy var인 이유)
- pop과 dismiss는 기본세팅되어있습니다. NavigationBar의 RightBarItems들에 대한 액션만 정의해주시면 됩니다.
- 높이 설정 필요X
```swift
navigationBar.snp.makeConstraints { make in
make.top.equalTo(view.safeAreaLayoutGuide)
make.leading.trailing.equalToSuperview()
}
```
- 사용할 수 있는 메서드들은 아래 extension으로 빼두었습니다. 함수 시그니처 위에 주석으로 설명을 달아두었습니다.
북마크와 마이페이지가 고정이라 해당 뷰컨으로 이동하는 로직 또한 내부에서 구현해둘 수 있었지만 NavigationBarView안에서 해당 뷰컨 객체들을 만들고 이동까지 시키는 것은 네비뷰의 책임에서 벗어나는 느낌이 들어서 위의 방법과 같이 action을 받게끔 했습니다.
VC객체들을 …
=> [FEAT] NavigationBar 구현 (#7)

LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift, LionHeart-iOS/LionHeart-iOS/Global/Utils/Palette.swift
- Color Asset쪽 rawValue에 대소문자 구분이 안되어있어서 color변경이 안되는 문제를 해결했습니다
- 공용 navigation 배경색 designSystem color로 변경
- Palette 파일수정
- LHNavigationBarView background컬러 변경
- Resolved: #15
=> [FIX] Color Asset 네이밍 변경(#15)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumDummyData.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
- 예시 더미데이터 작성
- 테이블뷰 구현
- 예시 더미데이터를 만들어 테이블뷰에 뿌려서 레이아웃을 잡아봤습니다.
multipliedBy 여기 안에서는 연산이 안되기 때문에(왜 안되는지는 몰라요..)
위 사진과 같이 따로 이넘으로 연산과정을 뺴주었습니다.
1. 아이폰14프로
|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 커리큘럼 테이블뷰 |<img src="https://github.com/gosopt-LionHeart/LionHeart-iOS/assets/70939232/5bb44e92-aae9-41ce-97fe-cd336466b98c" width="400"/>  |
3. 아이폰SE
|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 커리큘럼 테이블뷰 | <img src="https://github.com/gosopt-LionHeart/LionHeart-iOS/assets/70939232/31d5a055-6e70-4d89-8334-62149a220562" width="400"/> |
- Resolved: #19
=> [FEAT] CurriculumView TableView 구현 (#19)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Global/Utils/LoadingIndicator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift, LionHeart-iOS/LionHeart-iOS/Settings/Info.plist
- 네트워크 통신이 미처 끝나지 않은 상태에서 화면전환이 이루어지게 되면 통신 결과가 화면에 뒤늦게 반영되면서 사용자 경험을 저하시킬 수 있습니다.
- 따라서 네트워크 통신을 하는 동안의 지연시간을 위해 Loading Indicator View를 추가하였습니다.
```swift
final class LoadingIndicator {
static func showLoading() {
DispatchQueue.main.async {
guard let window = UIApplication.keyWindow else { return }
let loadingIndicatorView = UIActivityIndicatorView(style: .large)
loadingIndicatorView.color = .designSystem(.lionRed)
loadingIndicatorView.backgroundColor = .designSystem(.black)
loadingIndicatorView.frame = window.frame
window.addSubview(loadingIndicatorView)
loadingIndicatorView.startAnimating()
}
}
```
- 최상단 window를 가져와서 화면을 가득채운 IndicatorView를 만들어서 addSubView후에 indicator를 start합니다.
```swift
static func hideLoading() {
DispatchQueue.main.async {
let scenes = …
```
=> [FEAT] 로딩뷰 구현 (#91)

LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkRequest.swift
> http://3.34.174.158/api/v1/article?category=BUDGET
- 쿼리스트링으로 위와 같이 요청을 보내야하는 API.
```swift
func getArticleListByCategory(categoryString: String) async throws -> [ArticleDataByWeek] {
let urlRequest = try NetworkRequest(path: "/v1/article?category=\(categoryString)", httpMethod: .get).makeURLRequest(isLogined: true)
```
따라서 처음에 categoryString의 문자열만 받아서 문자열 보간법으로 위와 같이 넣어주었습니다. 하지만 Data는 가져와지는데 이후 JSONDecoding하는 과정에서 decode 에러가 계속해서 떴고, 처음에는 Data가 잘가져와지기에 무언가 DTO구조체 정의하는 부분에서 에러가 있었다고 생각해 해당 부분을 서버와 계속해서 확인하느라 굉장히 오랜시간이 걸렸고 결국 아무 문제가 없다는 것을 알 수 있었습니다.
**첫번째로 우리팀이 더 헷갈렸던 이유**는 해당 구조체를 쓰는 API가 두 군데인데 다른 API에서는 decode에러 없이 잘되었던  점이였습니다.
그렇게 찾다가 URL을 보기 시작했고 확인해본 결과
> http://3.34.174.158/api/v1/article%3fcategory=BUDGET
위와 같은 URL이였고, "?"가 encoding되면서 %3F로 바뀐 것이 문제의 원인이였습니다. 우리팀은 URLComponent를 …
=> [FIX] Query String JSON Decoding Error hotfix (#96)

LionHeart-iOS/LionHeart-iOS/Global/Protocols/ViewControllerServiceable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
네트워크 통신이 필요한 뷰에 로딩뷰를 적용하고 빌드를 통해 확인했습니다!
|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 로딩뷰 적용 |<img src="https://github.com/gosopt-LionHeart/LionHeart-iOS/assets/60292150/71fd994c-65ca-4bbf-a5a8-b8fbe2a203fb" width="300"/> |
- Resolved: #104
=> [FEAT] LoadingView뷰 추가 (#104)

LionHeart-iOS/LionHeart-iOS/Network/DTO/ArticleListByCategory/ArticleListByCategoryResponse.swift, LionHeart-iOS/LionHeart-iOS/Network/DTO/Curriculum/CurriculumResponse.swift, LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift, LionHeart-iOS/LionHeart-iOS/Network/Services/CurriculumViewService.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekRowZeroTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumListByWeekCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumListByWeekData.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift, LionHeart-iOS/LionHeart-iOS/Settings/Info.plist
기존에는 데이터가 1개밖에 존재하지 않아서 고려하지 못했던 문제들을 모든 데이터가 추가된 후의 상황에 맞게 로직을 모두 수정하였고 잘동작하는 것을 확인하였습니다.
- PR Point 1
- PR Point 2
|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| ex. 로그인 화면 | 파일첨부바람 |
- Resolved: #108
=> [FIX] 주차별 커리큘럼 조회 화면에서 오른쪽 버튼 클릭시 앱 터지는 에러 해결 (#108)

LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIView+.swift, LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Views/ArticleDetailTableView.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Cells/ChallengeDayCheckCollectionViewCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
- ArticleDetailView 레이아웃 수정
- Category Article List에서 ArticleDetailView 연결
- ChallengeViewController에 navibar 버튼 action 연결
- ChallengeViewController 에러핸들링 및 loadingView추가
1. ArticleDetailView bottom부분이 safeLayout기준으로 되어있어서 아래부분에 background부분이 보이는 문제를 해결헀습니다
2. ArticleDetailView 내부 tableView를 아래로 드래그했을때 backgroundColor가 figma와 다른부분을 변경했습니다
1. 카테고리별 아티클 리스트에서 articleDetailView로 articleID를 넘겨줘서 아티클상세뷰를 띄워주는 작업을 했습니다
2. 아티클리스트를 띄우는 과정에서 present를 사용해야하고 `isModalInPresentation`이나 `modalPresentationStyle`을 지정해줘야하는 번거로움이 있어서 UIViewController Extension에 detailViewController를 present해주는 메서드를 만들었습니다
```swift
extension UIViewController {
func presentArticleDetailFullScreen(articleID: Int) {
let articleDetailViewController = ArticleDetailViewController()
articleDetailViewController.setArticleId(id: …
```
=> [FIX] 1차 내부 QA (#114)

LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
- 커리큘럼메인에서 scrollToRow 분기처리
10개월 Section에만 5개의 주차가 있어서 40주차만 따로 분기처리 해주었습니다.
```swift
func scrollToUserWeek() {
guard let userInfoData else { return }
let userWeek = userInfoData.userWeekInfo
if userWeek == 40 {
let weekPerMonth = 4
let desireSection = (userWeek / weekPerMonth) - 2
let desireRow = (userWeek % weekPerMonth)
let indexPath = IndexPath(row: desireRow, section: desireSection)
curriculumViewDatas[desireSection].weekDatas[desireRow+4].isExpanded = true
self.curriculumTableView.reloadData()
self.curriculumTableView.scrollToRow(at: indexPath, at: .top, animated: false)
} else {
let weekPerMonth = 4
let desireSection = (userWeek / weekPerMonth) - 1
let desireRow = (userWeek % weekPerMonth)
let indexPath = IndexPath(row: desireRow, section: desireSection) …
```
=> [Fix] 커리큘럼메인에서 scrollToRow 분기처리(#117)

LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIButton+.swift, LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift, LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/BodyTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekRowZeroTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumUserInfoView.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
- 레이아웃 수정 및 present style 변경
- 1차 QA 후 필요한 행간 높이 조절 및 ViewWillAppear호출을 위해 present의 style을 fullScreen으로 변경하였습니다.
- HIG를 참고해 잘눌리지 않았던 버튼 영역을 44px로 늘려서 사용자 경험을 증진시켰습니다.
https://developer.apple.com/design/human-interface-guidelines/buttons
- Resolved: #121
=> [CHORE] 레이아웃 수정 및 사용자 경험 증진 (#121)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift, LionHeart-iOS/LionHeart-iOS/Network/API/BookmarkAPI.swift, LionHeart-iOS/LionHeart-iOS/Network/DTO/Bookmark/Response/BookmarkReponse.swift, LionHeart-iOS/LionHeart-iOS/Network/Services/BookmarkService.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
- 북마크 네트워크 레이어 분리했어요.
- 현재 북마크를 보여 주는 뷰에서는 북마크 데이터를 가져오는 get, 북마크 상태값을 보내는 post API를 호출하고, 동뷰 성뷰에서는 북마크 상태값을 보내는 post API만 호출하기 때문에 protocol을 크게 두 개로 나누었어요.
```swift 내 북마크
protocol BookmarkInOutServiceProtocol {
func postBookmark(model: BookmarkRequest) async throws
func getBookmark() async throws -> BookmarkAppData
}
// 동뷰, 성뷰
protocol BookmarkOutProtocol {
func postBookmark(model: BookmarkRequest) async throws
}
```
처음에는 이름만 다른 프로토콜이 여러 개가 생성되는 것 같아서 이런 식으로 분리를 했는데, 의존성 주입을 하다 보니 네이밍이 자연스럽지 않다는 생각이 들었어요.
```swift
let ArticleListByCategoryVC = ArticleListByCategoryViewController(serviceProcotol: BookmarkService(bookmarkAPIProtocol: BookmarkAPI(apiService: APIService())))
```
아티클 VC에 bookmarkservice, bookmark api 객체를 주입하는 게 어색할 수 있다는 생각이 들었어요.
그런데 현재 특정 뷰에서만 리팩토링이 진행되었기 때문에, 각각의 VC별로 …
=> [Refactor] #129 - 북마크 네트워크 레이어 분리

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Global/Extensions/UICollectionViewCell+.swift, LionHeart-iOS/LionHeart-iOS/Global/Protocols/CollectionHeaderViewRegisterDequeueProtocol.swift, LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHImageButton.swift, LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHLabel.swift, LionHeart-iOS/LionHeart-iOS/Global/Utils/Palette.swift, LionHeart-iOS/LionHeart-iOS/Network/Manager/MyPageManagerImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkDetailCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageAppSettingCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageCustomerServiceCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageProfileCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Model/MyPageModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Views/MyPageHeaderView.swift
- 북마크 디자인시스템 적용했어요.
- 마이페이지 VC는 의성 오빠가 디자인시스템 적용해 놓은 것 확인했고, 각각의 cell, headerView에도 디자인시스템 적용했어요.
- 마이페이지가 배지 프로필, 고객센터, 알림 세팅 총 세 개의 섹션으로 나뉘어져 있는데, 각각의 케이스를 enum으로 나누어서 구분했어요.
의성 오빠가 예전에 해 준 코드리뷰인데... https://github.com/gosopt-LionHeart/LionHeart-iOS/pull/51
> 연관값은 그 케이스에 연관되어있는 데이터를 가져온거니까 확인하면서 데이터를 가져올 필요도 없구요!
결국 현재 제가 enum으로 처리한 데이터가 더미이기 때문에, 이 의도가 제대로 반영이 됐는지는 모르겠네요 ㅠ__ㅠ
```swift
enum MyPageSection {
case badgeSection
case customerServiceSetion(section: MyPageSectionModel)
case appSettingSection(section: MyPageSectionModel)
static let sectionArray: [MyPageSection] = [.badgeSection,
.customerServiceSetion(section: MyPageSectionModel(sectionTitle: "고객센터",
cellTitle: ["공지사항","FAQ", "1:1 문의", "서비스 피드백", "이용약관", "개인보호 정책"])),
.appSettingSection(section: MyPageSectionModel(sectionTitle: …
```
=> [Refactor] #135 - 북마크 & 마이페이지 헤더뷰, 셀 디자인시스템 적용

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleCategoryCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/BookmarkCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ChallengeCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ArticleCategoryViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/BookmarkViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ChallengeViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TabbbarCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleCategortFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/BookmarkFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ChallengeFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleCategortFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/BookmarkFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ChallengeFactory.swift
- ArticleCategory관련 coordinator, viewcontroller에 factory pattern을 적용했습니다
- Challenge관련 coordinator, viewcontroller에 factory pattern을 적용했습니다
- Bookmark관련 coordinator, viewcontroller에 factory pattern을 적용했습니다
1. viewcontroller는 각각의 unique한 viewcontrollerable을 가지고 있고 해당interface는 coordinator(각각의 navigation interface type)와 데이터전달이 필요한 경우엔 해당 데이터를 추상화하고 있습니다
```swift
protocol BookmarkViewControllerable where Self: UIViewController {
var coordinator: BookmarkNavigation? { get set }
}
```
2. 각각의 coordinator는 unique한 factory interface를 가지고 있고 각각 필요한 viewcontrollerable타입을 return해줍니다
- coordinator의 init에 factory의 구현체를 외부 주입해줍니다
```swift
protocol BookmarkFactory {
func makeBookmarkViewController() -> BookmarkViewControllerable
}
```
3. 구현체(impl)는 저장속성이 없고 메서드만 호출하면되기때문에 struct로 구현햇습니다
```swift
struct …
```
=> [REFACTOR] ArticleCategory, Challenge, Bookmark Factory Pattern 적용(#143)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/AppCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/AuthCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/AuthFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/SpalshFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/SplashCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TabbbarCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnbardingViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
- Auth, Splash, Today coordinator, viewcontroller에 factory pattern을 적용했습니다.
1. 각각의 viewcontroller가 고유의 viewcontrollerable을 가지고 있어요. viewcontrollerable은 coordinator를 가지고 있고, 추가로 필요할 경우 데이터 전달 프로퍼티를 추상화하고 있어요.
```swift
protocol TodayViewControllerable where Self: UIViewController {
var coordinator: TodayNavigation? { get set }
}
```
2. 각각의 cordinatory가 고유의 factory 프로토콜을 가지고 있고, 해당 viewcontrollerable 타입을 return 하고 있어요.
```swift
protocol TodayFactory {
func makeTodayFactory() -> TodayViewControllerable
}
```
3. TodayFactoryImpl 구조체가 TodayFactory를 채택하여 필요한 로직을 구현해 주고 있습니다.
```swift
struct TodayFactoryImpl: TodayFactory {
func makeTodayFactory() -> TodayViewControllerable {
return TodayViewController(manager: TodayManagerImpl(articleService: ArticleServiceImpl(apiService: APIService())))
}
} …
```
=> [REFACTOR] - Auth, Splash, Today factory pattern 적용 (#144)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleCategoryCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/BookmarkCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ChallengeCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ArticleControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/CurriculumArticleByWeekControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/CurriculumControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MyPageControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MyPageFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MyPageFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MypageCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TabbbarCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayCoordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
- Curriculum, MyPage, Article Coordinator에 객체 생성 책임을 분리하기 위해 Factory를 만들어 주입시켜주었습니다. 
1. ViewController는 다른 ViewController에게 데이터 전달을 받을 수도 있어야하기 때문에 해당 메서드와 함께 coordinator(각 뷰컨마다의 navigation interface 타입)를 가지고 있습니다.
```swift
protocol ArticleControllerable where Self: UIViewController {
func setArticleId(id: Int?)
var coordinator: ArticleDetailModalNavigation? { get set }
}
```
2. 각각의 뷰컨은 Factory를 주입받기 위한 프로토콜을 가지고 있습니다. 이 때 Factory에서 리턴해주는 타입은 실제 객체의 타입이 아닌 프로토콜을 리턴함으로써 의존성을 분리시킵니다.
```swift
protocol ArticleFactory {
func makeArticleDetailViewController() -> ArticleControllerable
}
```
3. Factory를 실제로 구현한 FactoryImpl는 어떠한 속성도 없이 메서드만 존재하기 때문에 struct로 구성하였습니다.
```swift
struct ArticleFactoryImpl: ArticleFactory {
func makeArticleDetailViewController() -> ArticleControllerable {
let …
```
=> [REFACTOR] Curriculum, MyPage, Article Coordinator에 Factory Pattern 적용 (#145)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift, LionHeart-iOS/LionHeart-iOS/Global/Protocols/Coordinator.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/AppCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCategoryCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/BookmarkCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ChallengeCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/CurriculumCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/SplashCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TabbarCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TodayCoordinatorImpl.swift
- Coordinator에 Adaptor 패턴을 도입했습니다.
> 외부에서 알필요가 없는 부분을 감춤으로써 대상을 단순화하는 추상화의 한종류를 우리는 캡슐화라고한다.
그중에서도 메서드명을 통해서 어떤 변수를 가지고 있는지 혹은 어떤 객체와 연관성을 가지는지를 노골적으로 public interface에 드러내는 것 또한 캡슐화에 위반된다.         -_오브젝트_-
> 
위의 글을 참고해서 최대한 interface에서 캡슐화를 위반하지 않기 위해 `ViewController`에서는 화면전환을 하기 위한 메서드명에 화면전환 flow를 노골적으로 드러내지 않게 하기 위해서 유추할 수 있는 정보(예를 들어 ViewController의 이름)를 모두 배제하고 action을 위주로 메서드명을 구성했습니다.
```swift
protocol BarNavigation: AnyObject {
func navigationRightButtonTapped()
func navigationLeftButtonTapped()
}
protocol ArticleCategoryNavigation: ExpireNavigation, BarNavigation {
func articleListCellTapped(categoryName: String)
}
```
```swift
extension ArticleCategoryCoordinator: ArticleCategoryNavigation, ArticleListByCategoryNavigation {
func articleListCellTapped(categoryName: String) { ... …
```
=> [REFACTOR] Adaptor Pattern 도입 (#153)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/ThumnailTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Model/ArticleBlockType.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewModel/ArticleDetailViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewModel/ArticleDetailViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleFactory.swift
- ArticleDetail 기존 DataSource를 DiffableDataSource로 변경 
- ArticleDetail MVC-C -> MVVM(Combine)-C로 리팩토링
리팩토링 과정에서 팀원들과 이야기를 하던중, DiffableDataSource가 기존의 DataSource보다 성능상 이점이 있다는 것과, 변경되는 데이터에 대해 기본으로 제공되는 깔끔한 애니메이션을 통해서 더 나은 경험을 제공할 수 있는 DiffableDataSource로 변경하기로 결정되었습니다.
MVC-C에서 ViewController에 남아있는 마지막 데이터 로직을 분리하기 위한 ViewModel을 가지는 MVVM아키텍처로 변경했습니다. 이 때 ViewModel에 있는 데이터와 UI를 데이터 바인딩을 하기 위해서 Combine을 활용합니다.
그 중에서도 Input-Output구조를 채택함으로써 팀원들간에 통일된 구조를 가질 수 있었습니다. 또한, Input Output구조체를 통해서 ViewController와 ViewModel간에 주고받는 데이터를 한눈에 쉽게 알 수 있다는 장점이 있습니다.
```swift
struct ArticleDetailViewModelInput {
let viewWillAppear: PassthroughSubject<Void, Never>
let closeButtonTapped: PassthroughSubject<Void, Never>
let bookmarkButtonTapped: PassthroughSubject<Void, Never>
let scrollToTopButtonTapped: …
```
=> [REFACTOR] 아티클뷰 DiffableDataSource로 변경 및 MVVM(Combine)-C로 리팩토링 (#167)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Cells/ChallengeDayCheckCollectionViewCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ChallengeViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ChallengeFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ChallengeFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayArticleView.swift
- ChallengeVC에서 기존 로직에서 불필요한 부분을 지우고 메서드분리를 진행
- ChallengeVC의 기존 datasource를 DiffableDataSource로 리팩터링
- ChallengeVC MVVM(Combine)으로 리팩터링
기존에는 특정조건에따라서 cell의 UI컴포넌트에 직접접근해서 UI를 수정하는 방식이었습니다
코드가 길어지고 직관적이지 않다고 생각해서 아래와같은 코드로 수정헀습니다
```swift
let cell = ChallengeDayCheckCollectionViewCollectionViewCell.dequeueReusableCell(to: collectionView, indexPath: indexPath)
cell.configure(type: indexPath.item < input.daddyAttendances.count ? .read : .yet, input: input, indexPath: indexPath)
```
수정 후에는 cell의 type을 두가지로 나누고 type을 cell의 configure메서드에 전달해줍니다
```swift
func configure(type: ChallengeCellType, input: ChallengeData, indexPath: IndexPath) {
switch type {
case .read:
countLabel.text = input.daddyAttendances[indexPath.item]
backgroundColor = .designSystem(.background)
countLabel.textColor = …
```
=> [REFACTOR] ChallengeVC를 DiffableDataSource와 MVVM(Combine)으로 리팩터링

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Cells/ArticleCategoryCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryDiffableDataSource.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryDiffableModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewModel/ArticleCategoryViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewModel/ArticleCategoryViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/ThumnailTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Model/ArticleBlockType.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewModel/ArticleDetailViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewModel/ArticleDetailViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ArticleListByCategoryDiffableModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewModel/ArticleListByCategoryViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewModel/ArticleListByCategoryViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleCategoryViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleListByCategoryViewControllerable.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCategoryCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumListByWeekData.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleCategortFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleFactoryImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleCategortFactory.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleFactory.swift
- ArticleListByCategory 기존의 DataSource에서 DiffableDataSource로 변경
- ArticleListByCategory MVC-C에서 MVVM-C로 리팩토링
DiffableDataSource를 생성하기 위해서는 Hashable한 Item타입을 지정해주어야합니다.
```swift
enum ArticleListByCategoryItem: Hashable {
case article(data: ArticleDataByWeek)
}
```
따라서 위와 같은 enum을 구성하고 그 연관값으로 데이터를 전달합니다.
각 각의 Item은 Hashable하고, 모두 구분이 가능해야하기 때문에 이 때 전달되는 데이터는 `[]`, 배열의 형태가 아닌 단일값에 대한 타입(`CategoryImage`)입니다.
하지만 네트워크를 통해서 얻는 결과는 배열형태의 `[CategoryImage]`입니다. 따라서 이를 Item으로 넣어주기 위해서는 각각의 배열 요소를 위에서 생성한 enum의 category case의 연관값으로 바꿔주어야합니다. 이를 위해서 아래와 같이 코드를 작성하였습니다.
```swift
func applySnapshot(articleDatas: [ArticleDataByWeek]) {
var snapshot = NSDiffableDataSourceSnapshot<ArticleListByCategorySection, ArticleListByCategoryItem>()
snapshot.appendSections([.article])
let items = articleDatas.map { …
```
=> [REFACTOR] ArticleListByCategory Diffable 및 MVVM(Combine)-C 리팩토링 (#175)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Global/Extensions/UITabbarItem+.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TabbarCoordinatorImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/TabBar/TabBarViewController.swift
- 기존 TabbarCoordinator가 하나의 메서드에 모든 VC를 생성하고 설정해주는 로직이 모여있어 메서드분리를 진행해줬습니다
- 작업을 진행하면서 reference type의 이점을 살려 pure function으로 메서드를 분리하고 구현했습니다
- 간단한 작업이어서 pr은 작업한 내용정도로 마무리하겠습니다
tabbarController내부에 정의될 vc를 메서드를 통해서 분리해 구현해줬습니다
```swift
func startTodayArticleFlow(_ navi: UINavigationController, from parent: Coordinator?) {
let todayCoordinator = TodayCoordinatorImpl(navigationController: navi, factory: TodayFactoryImpl())
todayCoordinator.parentCoordinator = parent
navi.tabBarItem = .makeTabItem(.today)
parent?.children.append(todayCoordinator)
todayCoordinator.showTodayViewController()
}
```
coordinator가 AnyObject를 채택하는 프로토콜이라 reference를 참조해서 child에 append를 해도 괜찮을거같아서 메서드의 인자로 coordiantor프로토콜타입을 받아서 하나의 reference를 참조하도록 구현했습니다
기존 tabbarItem이 하드코딩 되어있던 부분이 있어서 enum을 활용해서 간단하게 구현했습니다 …
=> [REFACTOR] Tabbar Coordinator리팩터링(메서드분리)

LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewModel/ChallengeViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewModel/ChallengeViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewModel/MyPageViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnboardingViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/OnboardingViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/OnboardingViewModelImpl.swift
- ChallengeVC 점검
- MyPageVC 점검
- TodayVC 점검
- OnboardingVC 점검
네트워크 통신이 시작되고나면 lodingview가 화면에 표시되고 네트워크통신이끝나면 lodingview를 없애줍니다 버튼자체가 비동기적으로 호출되기에 호출시점에 처리를하기위해 해당 관련 stream을 따로 만들었습니다
```swift
let signUpSubject = signUpSubject
.flatMap { _ -> AnyPublisher<String, Never> in
return Future<String, NetworkError> { promise  in
Task {
do {
self.userSigningSubject.send(.start)
let passingData = UserOnboardingModel(kakaoAccessToken: self.kakaoAccessToken, pregnacny: input.pregenacy.value.pregnancy, fetalNickname: input.fetalNickname.value.fetalNickname)
try await self.manager.signUp(type: .kakao, onboardingModel: passingData)
self.userSigningSubject.send(.end)
self.navigatorSubject.send(.onboardingCompleted(passingData))
} catch {
promise(.failure(error as! NetworkError))
}
}
}
.catch { error in …
```
=> [REFACTOR] runloop, cell binding방식, 토스트메세지, loadingView 적용

LionHeart-iOS/LionHeart-iOS/Global/Literals/NameSpace.swift, LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHToast/LHToast.swift, LionHeart-iOS/LionHeart-iOS/Global/UserDefault/UserDefaultToken.swift, LionHeart-iOS/LionHeart-iOS/Scenes/ArticleDetail/Cells/ThumnailTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/ArticleDetail/ViewController/ArticleDetailViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/ArticleDetail/ViewModel/ArticleDetailViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/ArticleListByCategory/ViewController/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/Cell/CurriculumArticleByWeekTableViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/ViewController/CurriculumListWeekViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/ViewModel/CurriculumListWeekViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewModel/CurriculumViewViewModelImpl.swift, LionHeart-iOS/LionHeart-iOS/Scenes/Login/ViewModel/LoginViewModelImpl.swift
- CurriculumView
- CurriculumListWeekView
- ArticleDetail
- Login
각각의 뷰에 대해서 메인 스레드 관리, cell binding 방식 통일, 북마크 저장, 삭제, 요청 실패 토스트 메시지 추가했습니다.
ViewController의 bind메서드 내에서 UI에 데이터 바인딩을 하는 코드가 메인스레드에서 돌아가게끔 receive(on:) 메서드를 활용했습니다.
```swift
output.articleData
.receive(on: RunLoop.main)
.sink { ... }
```
Cell binding에 대한 내용은 https://github.com/Team-LionHeart/LionHeart-iOS/pull/187 해당 PR에서 자세히 설명해두었습니다!
- Resolved: #190
=> [REFACTOR] Runloop, cell binding방식, 토스트메세지, loadingView 적용 (#190)

LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHToast/LHToast.swift, LionHeart-iOS/LionHeart-iOS/Scenes/ArticleCategory/ViewController/ArticleCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/ArticleListByCategory/ViewController/ArticleListByCategoryViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewController/BookmarkViewController.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewModel/BookViewModel.swift, LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewModel/BookmarkViewModelImpl.swift
- 북마크, 주차별 아티클, 주차별 아티클 카테고리 VC 2차 리팩터링 코드 정리했습니다.
```swift
output.viewWillAppear
.receive(on: RunLoop.main)
.sink { [weak self] data in
self?.updateDiffableDataSource(sectionModel: data)
self?.hideLoading()
}
.store(in: &cancelBag)
output.bookmarkButtonTapped
.receive(on: RunLoop.main)
.sink { [weak self] (data, message) in
self?.updateDiffableDataSource(sectionModel: data)
LHToast.show(message: message)
}
.store(in: &cancelBag)
````
```swift
let bookmarkButtonTapped = input.bookmarkButtonTapped
.flatMap { indexPath -> AnyPublisher<(model: BookmarkAppData, message: String), Never> in
return Future<(model: BookmarkAppData, message: String), NetworkError> { promise in
Task {
do {
try await self.manager.postBookmark(model: .init(articleId: …
```
=> [REFACTOR] Runloop, cell binding방식, 토스트메세지, loadingView 적용 (#191)

LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj, LionHeart-iOS/LionHeart-iOS/Network/Base/APIService.swift, LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/ViewModel/CurriculumListWeekViewModelImpl.swift, LionHeart-iOS/LionHeart-iOSTests/Challenge/ServiceTests/ServiceTests.swift, LionHeart-iOS/LionHeart-iOSTests/URLSessionStub/JSONLoader.swift, LionHeart-iOS/LionHeart-iOSTests/URLSessionStub/URLSessionStub.swift
- Unit Test 관련 파일들 
```Ruby
ViewController당 커버리지 70% 이상
```
---
async await을 통한 기존 네트워크 통신은 urlsession객체의 data라는 메서드를 호출함으로써 진행됩니다
좀더 자세히 말하면 singleton으로 URLSession객체를 생성해서 data라는 메서드를 호출하면 URLRequest를 통한 네트워크통신을 해서 그 결과인 data와 response를 return해주는 방식입니다
> 즉, urlsession객체는 data라는 메서드를 구현하고 있는 상황입니다
> 
실직적으로 서버와 네트워크 통신을 하는 매개체는 `data(for: URLRequest)`라는 메서드이기때문에 우리가 네트워크통신을했을때 우리가 원하는 데이터가 올것이라는 예측에 의한 Testing을 위해서는 이 data라는 메서드를 우리가 원하는 방식으로(실제 네트워킹을 하지 않는 방식으로)만들어줘야합니다.
기존에 사용하던 네트워킹 객체를 test에서 사용해야 그 객체내부에서의 네트워크 통신이 문제없다는것이 보장되기에 원래쓰던(실제로 네트워킹을 하는 방식)방식으로도 사용을 할 수 있어야하고 이를 위해 `protocol`을 사용합니다.
```swift
protocol LHURLSession {
func data(for request: URLRequest) async throws -> (Data, URLResponse)
}
```
`LHURLSession`이라는 protocol은 data라는 메서드를 추상화하고 있고 `URLSession`과 `URLSessionStub`에 …
=> [TEST] API Unit Test 관련 파일들 추가 (#195)
